# Dependencies
markdown:         kramdown  
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Chewein's Blog
tagline:          ''
description:      '放荡不羁爱吃饭睡觉的伪码农'
url:              https://github.com/chewein

author:
  name:           'Chewein'
  url:            https://github.com/chewein

paginate:         10

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
# collections
collections:
  mycollection:
    output: true
